"""Shared model utilities reused across policy variants and decoders."""

from .flow_matching import (
    ActionFlowMatchTrainArtifacts,
    BlockCoupledActionFlowMatchTrainArtifacts,
    FrameAlignedActionFlowMatchTrainArtifacts,
    FlowMatchScheduler,
    build_action_flow_match_inference_scheduler,
    build_action_flow_match_train_artifacts,
    build_block_coupled_action_flow_match_train_artifacts,
    build_frame_aligned_action_flow_match_train_artifacts,
    build_flow_unipc_inference_scheduler,
    build_video_flow_match_inference_scheduler,
    build_video_flow_match_train_artifacts,
    denoised_actions_from_flow,
    denoised_video_latents_from_flow,
    reduce_frame_aligned_action_flow_match_loss,
    reduce_slot_aligned_action_flow_match_loss,
    reduce_video_flow_match_loss,
    sample_timestep_id,
)
from .flow_unipc_multistep_scheduler import FlowUniPCMultistepScheduler
from .register_sequence import (
    RegisterSequenceLayout,
    build_register_attention_mask,
    build_register_position_context,
    build_register_sequence_layout,
)
from .runtime_controls import (
    JointRuntimeSchedulers,
    RuntimeCachePolicy,
    RuntimeGuidanceConfig,
    RuntimeWarmupReference,
    build_joint_video_timestep_grid,
    build_joint_runtime_schedulers,
    build_unconditional_conditioning,
    combine_cfg_prediction,
    combine_joint_cfg_predictions,
    preserve_joint_observed_video_prefix,
    resolve_runtime_warmup_reference,
    resolve_runtime_guidance,
    resolve_runtime_cache_policy,
    should_update_cache_during_denoise,
)
from .rollout import RolloutCursor, advance_rollout_cursor
from .video_geometry import slice_token_grid_frames, unpatchify_video_tokens

__all__ = [
    "ActionFlowMatchTrainArtifacts",
    "BlockCoupledActionFlowMatchTrainArtifacts",
    "FrameAlignedActionFlowMatchTrainArtifacts",
    "FlowMatchScheduler",
    "FlowUniPCMultistepScheduler",
    "JointRuntimeSchedulers",
    "RuntimeCachePolicy",
    "RuntimeWarmupReference",
    "RegisterSequenceLayout",
    "RolloutCursor",
    "RuntimeGuidanceConfig",
    "build_joint_video_timestep_grid",
    "build_action_flow_match_inference_scheduler",
    "build_action_flow_match_train_artifacts",
    "build_block_coupled_action_flow_match_train_artifacts",
    "build_joint_runtime_schedulers",
    "build_frame_aligned_action_flow_match_train_artifacts",
    "build_flow_unipc_inference_scheduler",
    "build_register_attention_mask",
    "build_register_position_context",
    "build_register_sequence_layout",
    "build_unconditional_conditioning",
    "combine_cfg_prediction",
    "combine_joint_cfg_predictions",
    "preserve_joint_observed_video_prefix",
    "build_video_flow_match_inference_scheduler",
    "build_video_flow_match_train_artifacts",
    "denoised_actions_from_flow",
    "denoised_video_latents_from_flow",
    "advance_rollout_cursor",
    "reduce_frame_aligned_action_flow_match_loss",
    "reduce_slot_aligned_action_flow_match_loss",
    "reduce_video_flow_match_loss",
    "resolve_runtime_cache_policy",
    "resolve_runtime_warmup_reference",
    "resolve_runtime_guidance",
    "sample_timestep_id",
    "slice_token_grid_frames",
    "should_update_cache_during_denoise",
    "unpatchify_video_tokens",
]
