from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import shutil


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / ".docs_site"
PUBLIC_DOCS = REPO_ROOT / "docs"
NOTES = REPO_ROOT / "notes"
OUTPUT_SENTINEL = ".open_wam_generated_docs"
TEXT_SUFFIXES = {".csv", ".json", ".md", ".txt", ".yaml", ".yml"}

PRIVATE_REPLACEMENTS = (
    ("/path/to/private-resource", "${OPEN_WAM_REPO}"),
    ("/path/to/private-resource", "${OPEN_WAM_REPO}"),
    ("/path/to/private-resource", "${OPEN_WAM_ARTIFACT_ROOT}"),
    ("/path/to/private-resource", "${OPEN_WAM_ARTIFACT_ROOT}"),
    ("/path/to/private-resource", "${OPEN_WAM_ARTIFACT_ROOT}"),
    ("/simurgh2/datasets", "${OPEN_WAM_DATA_ROOT}"),
    ("/simurgh2", "${OPEN_WAM_SCRATCH_ROOT}"),
    ("/sailhome", "${HOME}"),
)
FORBIDDEN_PUBLIC_FRAGMENTS = (
    "/simurgh",
    "/afs/",
    "/sailhome",
    "private-user",
    "private-user",
    "WANDB_API_KEY",
    "api_key:",
    "secret:",
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Stage public docs and sanitized notes for MkDocs.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Generated MkDocs docs_dir.")
    parser.add_argument("--no-notes", action="store_true", help="Only stage public docs/, not notes/.")
    args = parser.parse_args()

    summary = build_docs_site(args.output, include_notes=not args.no_notes)
    print(json.dumps(summary, indent=2, sort_keys=True))


def build_docs_site(output: Path, *, include_notes: bool = True) -> dict[str, int | str]:
    output = _validate_output_dir(output)
    if output.exists():
        _clear_generated_output(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / OUTPUT_SENTINEL).write_text("generated by scripts/build_docs_site.py\n", encoding="utf-8")

    public_pages = _stage_markdown_tree(PUBLIC_DOCS, output)
    note_pages = 0
    note_assets = 0
    if include_notes:
        note_pages, note_assets = _stage_notes(output / "engineering-notes")

    leaks = scan_private_fragments(output)
    if leaks:
        formatted = "\n".join(f"{path}:{line}: {fragment}" for path, line, fragment in leaks[:20])
        raise SystemExit(f"Generated docs still contain private fragments:\n{formatted}")

    return {
        "docs_dir": str(output),
        "public_pages": public_pages,
        "note_pages": note_pages,
        "note_assets": note_assets,
        "private_leaks": len(leaks),
    }


def _validate_output_dir(output: Path) -> Path:
    raw_output = output.expanduser()
    for path in (raw_output, *raw_output.parents):
        if path.exists() and path.is_symlink():
            raise SystemExit(f"Refusing to use symlinked docs output path: {path}")

    resolved_output = raw_output.resolve()
    home = Path.home().resolve()
    if resolved_output == resolved_output.parent:
        raise SystemExit("Refusing to use the filesystem root as the generated docs output.")
    if resolved_output == home:
        raise SystemExit("Refusing to use the home directory as the generated docs output.")
    if resolved_output == REPO_ROOT:
        raise SystemExit("Refusing to use the repository root as the generated docs output.")
    if resolved_output.exists() and not resolved_output.is_dir():
        raise SystemExit(f"Refusing to use non-directory docs output path: {resolved_output}")
    if resolved_output.exists() and any(resolved_output.iterdir()) and not (resolved_output / OUTPUT_SENTINEL).is_file():
        raise SystemExit(
            f"Refusing to clear non-generated docs output directory: {resolved_output}. "
            f"Expected sentinel file {OUTPUT_SENTINEL!r}."
        )
    return resolved_output


def _clear_generated_output(output: Path) -> None:
    for child in output.iterdir():
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()


def scan_private_fragments(root: Path) -> list[tuple[str, int, str]]:
    leaks: list[tuple[str, int, str]] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES.union({".html"}):
            continue
        for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            for fragment in FORBIDDEN_PUBLIC_FRAGMENTS:
                if fragment in line:
                    leaks.append((str(path.relative_to(root)), line_number, fragment))
    return leaks


def _stage_markdown_tree(source: Path, target: Path) -> int:
    count = 0
    for path in sorted(source.rglob("*")):
        if not path.is_file():
            continue
        relative = _site_relative_path(path.relative_to(source))
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        if path.suffix.lower() == ".md":
            destination.write_text(_sanitize_markdown(path.read_text(encoding="utf-8")), encoding="utf-8")
            count += 1
        else:
            shutil.copy2(path, destination)
    return count


def _stage_notes(target: Path) -> tuple[int, int]:
    target.mkdir(parents=True, exist_ok=True)
    pages: list[tuple[Path, str]] = []
    assets = 0

    readme = NOTES / "README.md"
    readme_text = ""
    if readme.is_file():
        readme_text = _strip_first_heading(_sanitize_markdown(readme.read_text(encoding="utf-8"))).strip()

    for path in sorted(NOTES.rglob("*")):
        if not path.is_file():
            continue
        if path == readme:
            continue
        relative = _site_relative_path(path.relative_to(NOTES))
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        if path.suffix.lower() in TEXT_SUFFIXES:
            sanitized = _sanitize_markdown(path.read_text(encoding="utf-8"))
            destination.write_text(sanitized, encoding="utf-8")
        else:
            shutil.copy2(path, destination)
        if path.suffix.lower() == ".md":
            pages.append((relative, _page_title(sanitized, fallback=path.stem.replace("_", " ").title())))
        else:
            assets += 1

    index = _notes_index(readme_text, pages)
    (target / "index.md").write_text(index, encoding="utf-8")
    return len(pages) + 1, assets


def _site_relative_path(relative: Path) -> Path:
    if relative.name == "README.md":
        return relative.with_name("index.md")
    return relative


def _sanitize_markdown(text: str) -> str:
    for private, public in PRIVATE_REPLACEMENTS:
        text = text.replace(private, public)
    text = re.sub(r"\$\{OPEN_WAM_REPO\}/outputs/[^\s`)]+", "${OPEN_WAM_OUTPUT_ROOT}/...", text)
    text = re.sub(r"\$\{OPEN_WAM_ARTIFACT_ROOT\}/[^\s`)]+", "${OPEN_WAM_ARTIFACT_ROOT}/...", text)
    text = re.sub(r"\$\{OPEN_WAM_DATA_ROOT\}/[^\s`)]+", "${OPEN_WAM_DATA_ROOT}/...", text)
    return text


def _strip_first_heading(text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0].startswith("# "):
        return "\n".join(lines[1:]).lstrip()
    return text


def _page_title(text: str, *, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return fallback


def _notes_index(readme_text: str, pages: list[tuple[Path, str]]) -> str:
    lines = [
        "# Engineering Notes",
        "",
        "These pages are generated from `notes/` during the docs build. Private",
        "machine-local paths are rewritten to public placeholders before this",
        "directory is published.",
        "",
    ]
    if readme_text:
        lines.extend(["## Notes Overview", "", readme_text, ""])

    lines.extend(["## Published Notes", ""])
    for relative, title in pages:
        lines.append(f"- [{title}]({relative.as_posix()})")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    main()
