#!/usr/bin/env python
"""Evaluate one video-backbone export through the canonical VTA marginal."""

from __future__ import annotations

import argparse
from enum import Enum
import json
import math
import statistics
from dataclasses import replace
from pathlib import Path
from typing import Any

import torch

from open_wam.configs import (
    AttentionMode,
    DataConfig,
    ExperimentConfig,
    ReferenceCoreInitMode,
    load_experiment_config,
    validate_experiment_config_runtime_contract,
)
from open_wam.data import (
    build_train_val_latent_datasets,
    collate_latent_wam_samples,
    move_latent_wam_batch_to_device,
)
from open_wam.evals.video_prediction import rollout_causal_video_prediction
from open_wam.pipelines import build_variant_pipeline_from_config
from open_wam.runtime.provenance import collect_runtime_provenance
from open_wam.training.step_executor import LatentBatchAdapter
from open_wam.utils import resolve_transformer_dir_override, seed_everywhere


class GeometryMode(str, Enum):
    """Sampling geometry used by the matched checkpoint diagnostic."""

    TRAINING_RANDOM = "training_random"
    FIXED = "fixed"


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Score arbitrary video-backbone weights through the same causal "
            "video/VTA-marginal runtime and data contract."
        )
    )
    parser.add_argument("--cfg", "--config", dest="config", required=True)
    parser.add_argument(
        "--checkpoint",
        required=True,
        help="Checkpoint directory or exported transformer directory.",
    )
    parser.add_argument("--data-root", required=True)
    parser.add_argument("--empty-text-embedding", required=True)
    parser.add_argument("--reference-assets-root", required=True)
    parser.add_argument("--split", choices=("train", "val"), default="train")
    parser.add_argument("--num-samples", type=int, default=20)
    parser.add_argument("--shard-index", type=int, default=0)
    parser.add_argument("--num-shards", type=int, default=1)
    parser.add_argument(
        "--segment-frames",
        "--target-frames",
        dest="segment_frames",
        type=int,
        default=4,
        help="Number of target latent frames materialized for train-loss scoring.",
    )
    parser.add_argument("--max-train-chunk-size", type=int, default=4)
    parser.add_argument(
        "--train-window-size",
        "--window-size",
        dest="train_window_size",
        type=int,
        default=64,
    )
    parser.add_argument(
        "--geometry-mode",
        choices=tuple(mode.value for mode in GeometryMode),
        default=GeometryMode.TRAINING_RANDOM.value,
        help=(
            "Use the checkpoint's randomized training geometry or pin the "
            "requested chunk/window geometry for rollout-parity scoring."
        ),
    )
    parser.add_argument(
        "--rollout-frame-chunk-size",
        type=int,
        default=4,
        help="Future latent frames generated by the full-denoise diagnostic.",
    )
    parser.add_argument(
        "--rollout-chunk-horizons",
        default="1",
        help=(
            "Comma-separated recurrent rollout horizons. The largest horizon is "
            "generated once and every smaller value is scored as an exact prefix."
        ),
    )
    parser.add_argument(
        "--skip-train-metrics",
        action="store_true",
        help="Skip the stochastic training forward when only rollout drift is needed.",
    )
    parser.add_argument(
        "--save-latent-artifacts",
        action="store_true",
        help="Persist per-sample prediction/target tensors for later VAE metrics.",
    )
    parser.add_argument(
        "--text-source",
        choices=("correct", "next_task", "blank"),
        default="correct",
        help="Condition on the sample task, another task, or the blank embedding.",
    )
    parser.add_argument("--guidance-scale", type=float, default=None)
    parser.add_argument("--seed", type=int, default=1729)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--output-json", required=True)
    return parser


def _evenly_spaced_indices(length: int, count: int) -> tuple[int, ...]:
    if length <= 0:
        raise ValueError("Cannot sample an empty dataset.")
    if count <= 0:
        raise ValueError(f"--num-samples must be positive, got {count}.")
    count = min(int(count), int(length))
    return tuple(
        min(length - 1, math.floor((index + 0.5) * length / count))
        for index in range(count)
    )


def _summary(values: list[float]) -> dict[str, float]:
    if not values:
        raise ValueError("Cannot summarize an empty metric list.")
    return {
        "mean": statistics.fmean(values),
        "std": statistics.pstdev(values),
        "median": statistics.median(values),
        "min": min(values),
        "max": max(values),
    }


def _parse_chunk_horizons(value: str) -> tuple[int, ...]:
    try:
        horizons = tuple(sorted({int(item.strip()) for item in value.split(",")}))
    except ValueError as exc:
        raise ValueError(
            "--rollout-chunk-horizons must be comma-separated positive integers."
        ) from exc
    if not horizons or any(horizon <= 0 for horizon in horizons):
        raise ValueError(
            "--rollout-chunk-horizons must contain positive integers, "
            f"got {value!r}."
        )
    return horizons


def _shard_indexed_samples(
    indices: tuple[int, ...],
    *,
    shard_index: int,
    num_shards: int,
) -> tuple[tuple[int, int], ...]:
    if num_shards <= 0:
        raise ValueError(f"--num-shards must be positive, got {num_shards}.")
    if not 0 <= shard_index < num_shards:
        raise ValueError(
            "--shard-index must satisfy 0 <= shard_index < num_shards, "
            f"got shard_index={shard_index}, num_shards={num_shards}."
        )
    return tuple(
        (ordinal, dataset_index)
        for ordinal, dataset_index in enumerate(indices)
        if ordinal % num_shards == shard_index
    )


def _diagnostic_data_config(
    data_config: DataConfig,
    geometry_mode: GeometryMode,
) -> DataConfig:
    if geometry_mode is GeometryMode.TRAINING_RANDOM:
        return data_config
    return replace(
        data_config,
        sample_construction=replace(
            data_config.sample_construction,
            randomize_geometry=False,
        ),
    )


def _resolved_config(
    args: argparse.Namespace,
) -> tuple[ExperimentConfig, DataConfig, Path]:
    config = load_experiment_config(
        Path(args.config).expanduser().resolve(),
        checkpoint_runtime_compat=True,
    )
    transformer_dir = resolve_transformer_dir_override(
        args.checkpoint,
        option_name="--checkpoint",
    )
    geometry_mode = GeometryMode(args.geometry_mode)
    sample = replace(
        config.data.sample_construction,
        segment_min_frames=int(args.segment_frames),
        segment_max_frames=int(args.segment_frames),
        randomize_segment_length=False,
        randomize_segment_start=False,
        require_full_segment=True,
        # The model config must remain a valid maintained training contract.
        # A fixed diagnostic view is applied only to the dataset below.
        randomize_geometry=True,
        chunk_size=int(args.max_train_chunk_size),
        window_size=int(args.train_window_size),
    )
    config = replace(
        config,
        data=replace(
            config.data,
            local_root=str(Path(args.data_root).expanduser().resolve()),
            empty_text_embedding_path=str(
                Path(args.empty_text_embedding).expanduser().resolve()
            ),
            num_workers=0,
            sample_construction=sample,
        ),
        backbone=replace(
            config.backbone,
            pretrained_model_name_or_path=str(
                Path(args.reference_assets_root).expanduser().resolve()
            ),
            runtime_backbone_artifact_path=str(transformer_dir),
            load_reference_core_weights=True,
            load_wan_vae_frontend=False,
            load_text_conditioning=False,
            reference_core_init_mode=ReferenceCoreInitMode.VIDEO_ONLY,
            # FlexAttention's generated train kernel exceeds the shared-memory
            # limit on L40S. Dense SDPA implements the same prepared mask and
            # keeps this diagnostic portable across evaluation GPUs.
            attn_mode=AttentionMode.TORCH,
            train_attn_mode=AttentionMode.TORCH,
        ),
        training=replace(
            config.training,
            chunk_size=int(args.max_train_chunk_size),
            window_size=int(args.train_window_size),
        ),
        inference=replace(
            config.inference,
            frame_chunk_size=int(args.rollout_frame_chunk_size),
            guidance_scale=(
                config.inference.guidance_scale
                if args.guidance_scale is None
                else float(args.guidance_scale)
            ),
        ),
    )
    config = validate_experiment_config_runtime_contract(config)
    diagnostic_data_config = _diagnostic_data_config(config.data, geometry_mode)
    return config, diagnostic_data_config, transformer_dir


def _metric(output, name: str) -> float:
    value = output.decoder_output.metrics.get(name)
    if not isinstance(value, torch.Tensor) or value.numel() != 1:
        raise ValueError(f"Video marginal did not report scalar metric {name!r}.")
    return float(value.detach().float().cpu().item())


def _train_video_flow_regions(output, *, startup_frames: int) -> dict[str, float]:
    envelope = output.policy_output.decoder_artifacts
    if envelope is None:
        raise ValueError("Video marginal did not emit train decoder artifacts.")
    payload = envelope.payload
    video = getattr(payload, "video", payload)
    flow_pred = getattr(video, "flow_pred", None)
    targets = getattr(video, "targets", None)
    loss_mask = getattr(video, "future_loss_mask", None)
    if not all(isinstance(value, torch.Tensor) for value in (flow_pred, targets, loss_mask)):
        raise TypeError(
            "Video marginal train artifacts must expose flow prediction, target, "
            "and future loss mask tensors."
        )
    assert isinstance(flow_pred, torch.Tensor)
    assert isinstance(targets, torch.Tensor)
    assert isinstance(loss_mask, torch.Tensor)
    squared_error = (flow_pred.float() - targets.float()).square()
    expanded_mask = loss_mask.to(device=squared_error.device, dtype=torch.bool)
    if tuple(expanded_mask.shape) != tuple(squared_error.shape):
        expanded_mask = expanded_mask.expand_as(squared_error)
    valid_frames = expanded_mask.any(dim=(0, 1, 3, 4)).nonzero(as_tuple=False).flatten()
    if valid_frames.numel() < 1:
        raise ValueError("Video marginal train artifacts have no supervised frames.")

    def masked_mean(frame_indices: torch.Tensor) -> float:
        selected_error = squared_error[:, :, frame_indices]
        selected_mask = expanded_mask[:, :, frame_indices]
        return float(selected_error.masked_select(selected_mask).mean().item())

    first_count = min(int(startup_frames), int(valid_frames.numel()))
    metrics = {
        "startup_frames_train_video_flow_loss": masked_mean(
            valid_frames[:first_count]
        ),
    }
    if int(valid_frames.numel()) > first_count:
        metrics["later_frames_train_video_flow_loss"] = masked_mean(
            valid_frames[first_count:]
        )
    return metrics


def _rollout_metrics(
    rollout,
    *,
    future_frames: int | None = None,
) -> dict[str, float]:
    observed = int(rollout.observed_latent_frames)
    available_future = int(rollout.predicted_latents.shape[2]) - observed
    target_future = int(rollout.target_latents.shape[2]) - observed
    future = (
        int(rollout.future_latent_frames)
        if future_frames is None
        else int(future_frames)
    )
    if future <= 0 or future > min(available_future, target_future):
        raise ValueError(
            "Requested rollout metric horizon exceeds available prediction/target "
            f"frames: requested={future}, predicted={available_future}, "
            f"target={target_future}."
        )
    predicted = rollout.predicted_latents[:, :, observed : observed + future].float()
    target = rollout.target_latents[:, :, observed : observed + future].float()
    context = rollout.target_latents[:, :, observed - 1 : observed].float()
    static = context.expand_as(target)
    predicted_sequence = torch.cat([context, predicted], dim=2)
    target_sequence = torch.cat([context, target], dim=2)
    predicted_delta = predicted_sequence[:, :, 1:] - predicted_sequence[:, :, :-1]
    target_delta = target_sequence[:, :, 1:] - target_sequence[:, :, :-1]
    predicted_displacement = predicted[:, :, -1] - context[:, :, 0]
    target_displacement = target[:, :, -1] - context[:, :, 0]
    flattened_predicted = predicted_displacement.flatten(start_dim=1)
    flattened_target = target_displacement.flatten(start_dim=1)
    cosine = torch.nn.functional.cosine_similarity(
        flattened_predicted,
        flattened_target,
        dim=1,
        eps=1e-8,
    ).mean()
    future_mse = (predicted - target).square().mean()
    static_mse = (static - target).square().mean()
    return {
        "full_denoise_future_latent_mse": float(future_mse.item()),
        "static_baseline_future_latent_mse": float(static_mse.item()),
        "model_vs_static_mse_ratio": float(
            (future_mse / static_mse.clamp_min(1e-12)).item()
        ),
        "temporal_delta_latent_mse": float(
            (predicted_delta - target_delta).square().mean().item()
        ),
        "endpoint_displacement_latent_mse": float(
            (predicted_displacement - target_displacement).square().mean().item()
        ),
        "endpoint_displacement_cosine": float(cosine.item()),
        "predicted_motion_energy": float(predicted_delta.square().mean().item()),
        "target_motion_energy": float(target_delta.square().mean().item()),
    }


def _horizon_metrics(
    rollout,
    *,
    chunk_horizons: tuple[int, ...],
    frame_chunk_size: int,
) -> dict[str, float]:
    metrics: dict[str, float] = {}
    for chunk_horizon in chunk_horizons:
        prefix = f"h{chunk_horizon}_"
        horizon_metrics = _rollout_metrics(
            rollout,
            future_frames=int(chunk_horizon) * int(frame_chunk_size),
        )
        metrics.update(
            {f"{prefix}{name}": value for name, value in horizon_metrics.items()}
        )
    return metrics


def _save_latent_artifact(
    *,
    root: Path,
    ordinal: int,
    dataset_index: int,
    rollout,
    metadata: dict[str, Any],
) -> str:
    observed = int(rollout.observed_latent_frames)
    path = root / f"sample_{ordinal:04d}_dataset_{dataset_index:06d}.pt"
    root.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "observed_latents": rollout.target_latents[:, :, :observed]
            .detach()
            .cpu(),
            "predicted_future_latents": rollout.predicted_latents[:, :, observed:]
            .detach()
            .cpu(),
            "target_future_latents": rollout.target_latents[:, :, observed:]
            .detach()
            .cpu(),
            "metadata": metadata,
        },
        path,
    )
    return str(path)


def _batch_with_text_source(
    batch,
    *,
    dataset,
    dataset_index: int,
    text_source: str,
):
    source_task = None if batch.task_text is None else batch.task_text[0]
    if text_source == "correct":
        return batch, source_task
    if text_source == "blank":
        if batch.negative_text_context is None:
            raise ValueError("Blank-text evaluation requires a negative text embedding.")
        return (
            replace(
                batch,
                task_text=("",),
                text_context=batch.negative_text_context,
            ),
            "",
        )
    for offset in range(1, len(dataset)):
        alternate_index = (int(dataset_index) + offset) % len(dataset)
        alternate_sample = dataset[alternate_index]
        if alternate_sample.task_text == source_task:
            continue
        alternate_batch = collate_latent_wam_samples([alternate_sample])
        if alternate_batch.text_context is None:
            raise ValueError("Alternate task sample has no positive text embedding.")
        return (
            replace(
                batch,
                task_text=alternate_batch.task_text,
                text_context=alternate_batch.text_context.to(
                    device=batch.video_latents.device,
                    dtype=batch.video_latents.dtype,
                ),
            ),
            alternate_batch.task_text[0],
        )
    raise ValueError("Dataset does not contain a second task for text ablation.")


def main() -> None:
    args = build_argument_parser().parse_args()
    if args.segment_frames <= 0:
        raise ValueError(
            f"--segment-frames must be positive, got {args.segment_frames}."
        )
    if args.max_train_chunk_size <= 0:
        raise ValueError(
            "--max-train-chunk-size must be positive, got "
            f"{args.max_train_chunk_size}."
        )
    if args.train_window_size <= 0:
        raise ValueError(
            f"--train-window-size must be positive, got {args.train_window_size}."
        )
    if args.rollout_frame_chunk_size <= 0:
        raise ValueError(
            "--rollout-frame-chunk-size must be positive, got "
            f"{args.rollout_frame_chunk_size}."
        )
    chunk_horizons = _parse_chunk_horizons(args.rollout_chunk_horizons)
    required_target_frames = int(max(chunk_horizons)) * int(
        args.rollout_frame_chunk_size
    )
    if int(args.segment_frames) < required_target_frames:
        raise ValueError(
            "--segment-frames must cover the largest recurrent rollout horizon: "
            f"segment_frames={args.segment_frames}, required={required_target_frames}."
        )
    config, diagnostic_data_config, transformer_dir = _resolved_config(args)
    train_dataset, val_dataset = build_train_val_latent_datasets(
        diagnostic_data_config
    )
    dataset = train_dataset if args.split == "train" else val_dataset
    if dataset is None:
        raise ValueError(
            f"The selected config does not provide a {args.split!r} dataset."
        )
    all_indices = _evenly_spaced_indices(len(dataset), args.num_samples)
    indexed_samples = _shard_indexed_samples(
        all_indices,
        shard_index=int(args.shard_index),
        num_shards=int(args.num_shards),
    )
    if not indexed_samples:
        raise ValueError(
            "The requested shard contains no samples; reduce --num-shards or "
            "increase --num-samples."
        )

    device = torch.device(args.device)
    pipeline = build_variant_pipeline_from_config(config).to(device)
    pipeline.eval()
    adapter = LatentBatchAdapter()
    records: list[dict[str, Any]] = []
    with torch.inference_mode():
        for ordinal, dataset_index in indexed_samples:
            sample_seed = int(args.seed) + ordinal * 1_000_003
            seed_everywhere(sample_seed)
            batch = move_latent_wam_batch_to_device(
                collate_latent_wam_samples([dataset[dataset_index]]),
                device,
            )
            source_task = None if batch.task_text is None else batch.task_text[0]
            batch, conditioning_task = _batch_with_text_source(
                batch,
                dataset=dataset,
                dataset_index=dataset_index,
                text_source=args.text_source,
            )
            train_metrics: dict[str, float] = {}
            if not args.skip_train_metrics:
                seed_everywhere(sample_seed)
                prepared = adapter.prepare(batch)
                train_output = pipeline.forward_train_from_latents(
                    prepared.video_latents,
                    prepared.policy_batch,
                    canonical_video=prepared.canonical_video,
                    text_context=prepared.text_context,
                    negative_text_context=prepared.negative_text_context,
                )
                train_metrics = {
                    "video_flow_loss": _metric(train_output, "video_only_flow_loss"),
                    "one_step_denoised_latent_mse": _metric(
                        train_output,
                        "latent_mse",
                    ),
                    **_train_video_flow_regions(
                        train_output,
                        startup_frames=int(args.rollout_frame_chunk_size),
                    ),
                }
            seed_everywhere(sample_seed)
            rollout = rollout_causal_video_prediction(
                pipeline,
                batch,
                num_chunks=max(chunk_horizons),
            )
            metadata = batch.metadata[0]
            record = {
                "ordinal": ordinal,
                "dataset_index": int(dataset_index),
                "episode_index": int(metadata.get("episode_index", -1)),
                "task_index": int(metadata.get("task_index", -1)),
                "source_task": source_task,
                "conditioning_task": conditioning_task,
                "sample_start_frame": int(metadata.get("sample_start_frame", -1)),
                "target_frame_count": int(batch.video_latents.shape[2]),
                "frame_shift": int(metadata.get("frame_shift", 0)),
                "sampled_chunk_size": int(metadata["sampled_chunk_size"]),
                "sampled_window_size": int(metadata["sampled_window_size"]),
                "sample_seed": sample_seed,
                **train_metrics,
                **_horizon_metrics(
                    rollout,
                    chunk_horizons=chunk_horizons,
                    frame_chunk_size=int(args.rollout_frame_chunk_size),
                ),
            }
            if args.save_latent_artifacts:
                artifact_metadata = {
                    **record,
                    "latent_layout": metadata.get("latent_layout"),
                }
                record["latent_artifact"] = _save_latent_artifact(
                    root=Path(args.output_json).expanduser().resolve().parent
                    / f"{Path(args.output_json).stem}_latents",
                    ordinal=ordinal,
                    dataset_index=int(dataset_index),
                    rollout=rollout,
                    metadata=artifact_metadata,
                )
            records.append(record)
            print(json.dumps(record, sort_keys=True), flush=True)

    train_metric_names = (
        "video_flow_loss",
        "startup_frames_train_video_flow_loss",
        "later_frames_train_video_flow_loss",
        "one_step_denoised_latent_mse",
    )
    rollout_metric_names = tuple(
        f"h{horizon}_{name}"
        for horizon in chunk_horizons
        for name in (
            "full_denoise_future_latent_mse",
            "static_baseline_future_latent_mse",
            "model_vs_static_mse_ratio",
            "temporal_delta_latent_mse",
            "endpoint_displacement_latent_mse",
            "endpoint_displacement_cosine",
            "predicted_motion_energy",
            "target_motion_energy",
        )
    )
    metric_names = train_metric_names + rollout_metric_names
    report = {
        "schema_version": "open_wam.video_marginal_checkpoint_eval.v1",
        "config": str(Path(args.config).expanduser().resolve()),
        "transformer_dir": str(transformer_dir),
        "data_root": str(Path(args.data_root).expanduser().resolve()),
        "split": args.split,
        "segment_frames": int(args.segment_frames),
        "max_train_chunk_size": int(args.max_train_chunk_size),
        "train_window_size": int(args.train_window_size),
        "geometry_mode": GeometryMode(args.geometry_mode).value,
        "rollout_frame_chunk_size": int(args.rollout_frame_chunk_size),
        "rollout_chunk_horizons": list(chunk_horizons),
        "skip_train_metrics": bool(args.skip_train_metrics),
        "text_source": args.text_source,
        "guidance_scale": float(config.inference.guidance_scale),
        "seed": int(args.seed),
        "sample_indices": [dataset_index for _, dataset_index in indexed_samples],
        "global_sample_indices": list(all_indices),
        "shard_index": int(args.shard_index),
        "num_shards": int(args.num_shards),
        "provenance": collect_runtime_provenance(
            config_path=args.config,
            checkpoint_path=transformer_dir,
            dataset_root=args.data_root,
        ),
        "metrics": {
            name: _summary([float(record[name]) for record in records])
            for name in metric_names
            if all(name in record for record in records)
        },
        "records": records,
    }
    output_path = Path(args.output_json).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"output_json": str(output_path), **report["metrics"]}, indent=2))


if __name__ == "__main__":
    main()
