"""Stage-aware visual tower shared across policy variants."""

from .contracts import (
    DecodedFeatureLayout,
    RegisterSequenceComponents,
    RegisterSequenceSemantics,
    StructuredAttentionContext,
    StructuredBlockSemantics,
    StructuredFrequencyBundle,
    VisualCoreInput,
    VisualCoreOutput,
    VisualDecodeOutput,
    VisualFrontendOutput,
    VisualIntermediateReadout,
    VisualReadoutRequest,
    VisualSequenceMetadata,
    VisualStageOutputs,
)
from .runtime_programs import (
    RuntimeProgramSpec,
    RuntimeStepInput,
    RuntimeStepOutput,
    build_chunked_dual_stream_exact_inference_program,
    build_chunked_dual_stream_exact_train_program,
    build_dense_runtime_program,
    build_register_sequence_runtime_program,
    build_single_stream_exact_runtime_program,
)
from .reference_transformer import build_reference_transformer, preferred_reference_dtype
from .shared_transformer_support import (
    SharedTransformerAttention,
    SharedTransformerRotaryPositionalEmbedding,
    SharedTransformerTimeEmbedding,
    apply_rotary_emb,
    feed_forward_with_materialized_params,
    layer_norm_with_materialized_params,
    linear_with_materialized_params,
    materialize_runtime_parameter,
    rms_norm_with_materialized_weight,
    select_chunk_slices,
)
from .stream_adapters import PreparedStreamInput, SharedRuntimeStreamAdapters, StreamInputAdapterSpec
from .stream_heads import StreamOutputHeadSpec
from .tower import VisualTower

__all__ = [
    "build_reference_transformer",
    "build_chunked_dual_stream_exact_inference_program",
    "build_chunked_dual_stream_exact_train_program",
    "build_dense_runtime_program",
    "build_register_sequence_runtime_program",
    "build_single_stream_exact_runtime_program",
    "DecodedFeatureLayout",
    "PreparedStreamInput",
    "preferred_reference_dtype",
    "RegisterSequenceComponents",
    "RegisterSequenceSemantics",
    "SharedRuntimeStreamAdapters",
    "StreamInputAdapterSpec",
    "StreamOutputHeadSpec",
    "StructuredAttentionContext",
    "StructuredBlockSemantics",
    "StructuredFrequencyBundle",
    "SharedTransformerAttention",
    "SharedTransformerRotaryPositionalEmbedding",
    "SharedTransformerTimeEmbedding",
    "RuntimeProgramSpec",
    "RuntimeStepInput",
    "RuntimeStepOutput",
    "apply_rotary_emb",
    "feed_forward_with_materialized_params",
    "layer_norm_with_materialized_params",
    "linear_with_materialized_params",
    "materialize_runtime_parameter",
    "rms_norm_with_materialized_weight",
    "select_chunk_slices",
    "VisualCoreInput",
    "VisualCoreOutput",
    "VisualDecodeOutput",
    "VisualFrontendOutput",
    "VisualIntermediateReadout",
    "VisualReadoutRequest",
    "VisualSequenceMetadata",
    "VisualStageOutputs",
    "VisualTower",
]
